/*
 * Generated by classgen, version 1.3
 * 26/10/12 17:14
 */
package org.tree;

public class ExpChar extends Expressao {

  public String c;

  public ExpChar (String c) {
    this.c = c;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("ExpChar(\n");
    buffer.append("  "+tab+c);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [ExpChar]");
    return buffer.toString();
  }
}
