/*
 * Generated by classgen, version 1.3
 * 26/10/12 16:39
 */
package org.tree;

public class ExpFloat extends Expressao {

  public Float fl;

  public ExpFloat (Float fl) {
    this.fl = fl;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("ExpFloat(\n");
    buffer.append("  "+tab+fl);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [ExpFloat]");
    return buffer.toString();
  }
}
