/*
 * Generated by classgen, version 1.3
<<<<<<< HEAD
 * 10/23/12 1:51 PM
=======
 * 23/10/12 13:40
>>>>>>> 39cd9c49ca1beb2bbcd275d14e21c8067c223f31
 */
package org.tree;

public abstract class Expressao implements SyntaxNode {

  public Tipo tpo;
  public Object val;
  public Integer linha;
  public Integer coluna;
  private SyntaxNode parent;

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public abstract void accept(Visitor visitor);
  public abstract void childrenAccept(Visitor visitor);
  public abstract void traverseTopDown(Visitor visitor);
  public abstract void traverseBottomUp(Visitor visitor);
  public String toString() {
    return toString("");
  }

  public abstract String toString(String tab);
}
