/*
 * Generated by classgen, version 1.3
<<<<<<< HEAD
 * 26/10/12 16:39
=======
 * 10/26/12 3:39 PM
>>>>>>> 418173061f0eac84457fe3190233b308f007680a
 */

package org.tree;

public interface SyntaxNode {

  public void accept(Visitor visitor);

  public void childrenAccept(Visitor visitor);
  public void traverseBottomUp(Visitor visitor);
  public void traverseTopDown(Visitor visitor);

  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
