/*
 * Generated by classgen, version 1.3
<<<<<<< HEAD
 * 10/23/12 1:51 PM
=======
 * 23/10/12 13:40
>>>>>>> 39cd9c49ca1beb2bbcd275d14e21c8067c223f31
 */
package org.tree;

public class TermoParenteses extends Expressao {

  public Expressao exp;

  public TermoParenteses (Expressao exp) {
    this.exp = exp;
    if (exp != null) exp.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (exp != null) exp.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (exp != null) exp.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (exp != null) exp.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("TermoParenteses(\n");
      if (exp != null)
        buffer.append(exp.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [TermoParenteses]");
    return buffer.toString();
  }
}
