
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 26 17:57:40 BRST 2012
//----------------------------------------------------

package org.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LFLOAT = 16;
  public static final int SCANF = 25;
  public static final int MULT = 40;
  public static final int CHAR = 12;
  public static final int SOMA = 42;
  public static final int LCHAVE = 4;
  public static final int LPAREN = 2;
  public static final int INT = 13;
  public static final int RCHAVE = 5;
  public static final int E = 32;
  public static final int RPAREN = 3;
  public static final int LCHAR = 17;
  public static final int OU = 29;
  public static final int VIRG = 8;
  public static final int DIV = 39;
  public static final int LINT = 15;
  public static final int MAIN = 23;
  public static final int IF = 22;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int MAIOR = 36;
  public static final int error = 1;
  public static final int INCLUDE = 20;
  public static final int DIF = 38;
  public static final int MENOR = 37;
  public static final int VOID = 27;
  public static final int IDF = 19;
  public static final int EQ = 33;
  public static final int PRINTF = 24;
  public static final int PTVIRG = 11;
  public static final int ATRIB = 31;
  public static final int NEG = 30;
  public static final int SHARP = 10;
  public static final int ELSE = 21;
  public static final int WHILE = 28;
  public static final int MAIEQ = 34;
  public static final int FLOAT = 14;
  public static final int MENEQ = 35;
  public static final int STRING = 18;
  public static final int LCOLCH = 6;
  public static final int SUB = 41;
  public static final int ECOM = 9;
  public static final int RCOLCH = 7;
}

